### ISSUE TITLE
NestedHyperlinkedRelatedField should default use_pk_only_optimization to False

### ISSUE THREAD

**Issue by porksmash** [alanjds/drf-nested-routers#101]
NestedHyperlinkedRelatedField, which inherits from DRF's HyperlinkedRelatedField, defaults to using a [PKOnlyObject](https://github.com/encode/django-rest-framework/blob/ee1a9fcef659d0a5885712575562acb71a502f21/rest_framework/relations.py#L61) optimized object rather than the full model instance if the lookup_field kwarg is `'pk'`. However, this won't work for the nested relationship lookup process because the object literally only has a `pk` field and any attempt to examine other fields results in an exception.

By overriding use_pk_only_optimization() in the field to return False, it guarantees the full objects will be used and then nested lookups will work correctly. I'll submit a PR too.

**Comment by alanjds** [comment]
Thanks for reporting and even more for the PR.

**Comment by porksmash** [comment]
@alanjds I just noticed that PR #97 also included the same fix and more, and now there are two `use_pk_only_optimization()` definitions in `NestedHyperlinkedRelatedField`. My apologies for not examining existing pull requests.

**Comment by alanjds** [comment]
Me too. Thanks Travis it is already fixed. Just waiting his bless on the new code.

**Comment by alanjds** [comment]
Done. Travis is happy :)
