### ISSUE TITLE
create new nested object good practices

### ISSUE THREAD

**Issue by Calion54** [alanjds/drf-nested-routers#103]
Hi,

I would like create a nested object. So I have a modelViewSet and I ModelSerializer. I overide the create method in ModelSerizer. But does anyone have a good example of overriding .create() in ModelViewSet for the nested model?

Actually, I retrieve the parent resource  like this : self.context['request'].parser_context['kwargs']['publication_identifier'] but It's ugly !!!

Thank you,

**Comment by alanjds** [comment]
The README got updated w/ a `viewsets.ModelViewSet` exemple. Just changed the `get_queryset()`!

Please take a look. I will close the issue. Reopen if needed.

Best,
A.
