### ISSUE TITLE
Nested URLS Do Not Show Up DRF Auto-Generated Documentation

### ISSUE THREAD

**Issue by mrname** [alanjds/drf-nested-routers#104]
When using the [DRF Auto-Documentation](http://www.django-rest-framework.org/topics/documenting-your-api/#built-in-api-documentation) feature, nested URL's do not show up.

I will try to look into the issue myself, but wanted to log it for posterity.

**Comment by alanjds** [comment]
The future me thanks the past you for logging to the posterity.

**Comment by alanjds** [comment]
And thanks again for pointing it. I was not aware of this feature

**Comment by alanjds** [comment]
And thanks again for pointing it. I was not aware of this feature

**Comment by ChristianKreuzberger** [comment]
Interesting enough, this doesn't seem to be an issue with the drf-nested-routers, as coreapis schema generation nicely contains nested endpoints (in my case I have a history endpoint below each contact):
```json
 "contacts": {
        "history": {
            "list": { "some_attributes_for_contact_history_list": {} },
            "read": { "some_attributes_for_contact_history_read": {} }
        },
        "list": {},
        "read": {},
        "update": {},
}
```

It seems the problem only exists for rendering the "docs" frontend page

**Comment by ChristianKreuzberger** [comment]
Hm, I know yesterday this didn't work on my home computer (and yes I did run ``pip install -r requirements.txt --upgrade``, I had the latest versions of everything). I'm now in my office, and I tried it and it does kind of work:

![apidoc](https://user-images.githubusercontent.com/1684296/30148162-79ab058e-93a2-11e7-98f0-1f58210f7a7b.png)

**Comment by mrname** [comment]
That's peculiar @ChristianKreuzberger. I bumped into this issue out in the wild in a production project. I will try to reproduce in a more contained environment.

**Comment by Amoki** [comment]
I have the same issue. Does anyone have a clue about what is happening ?

**Comment by alanjds** [comment]
Does not is it solved? I remember to had read some talk about it on our Gitter channel.

**Comment by c17r** [comment]
So what I tried:

```python
from django.db import models
from rest_framework import serializers
from rest_framework import viewsets


class Parent(models.Model):
    name = models.CharField(max_length=255)


class Child(models.Model):
    parent = models.ForeignKey('Parent')
    value = models.CharField(max_length=255)


class ParentSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Parent
        fields = ('name', )


class ChildSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Child
        fields = ('value', )


class ParentViewSet(viewsets.ModelViewSet):
    """
    Parents API
    """
    queryset = Parent.objects.all()
    serializer_class = ParentSerializer


class ChildViewSet(viewsets.ModelViewSet):
    """
    Child API
    """
    queryset = Child.objects.all()
    serializer_class = ChildSerializer
```
with
```python
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework import routers
from rest_framework_nested import routers as nested_routers
from rest_framework.documentation import include_docs_urls

from myapp import models

router = routers.DefaultRouter()
router.register(r'parents', models.ParentViewSet)
router.register(r'children', models.ChildViewSet)

nested = routers.DefaultRouter()
nested.register(r'np', models.ParentViewSet)

nested_parent = nested_routers.NestedDefaultRouter(nested, r'np', lookup='p')
nested_parent.register(r'npcs', models.ChildViewSet, base_name='npc')

urlpatterns = [
    url(r'drf/', include(router.urls)),

    url(r'nested/', include(nested.urls)),
    url(r'nested/', include(nested_parent.urls)),

    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'docs/', include_docs_urls(title='My API Title')),
]
```
which shows in the doc browser:
<img width="762" alt="screen shot 2018-02-06 at 11 10 08 pm" src="https://user-images.githubusercontent.com/148640/35898184-012581ca-0b93-11e8-8554-f37e49beb2c9.png">

So it appears to work? Or am I missing something?

**Comment by alanjds** [comment]
I tried it too and seems to be working.

Will close the issue. Please reopen if needed.

**Comment by H4kor** [comment]
For anyone else running in this problem: Check that you are using the **openapi** AutoSchema, not the coreapi version. This fixed the problem for me.

```
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.openapi.AutoSchema",
 }
```
