### ISSUE TITLE
Validate lookup (and provide helpful error)

### ISSUE THREAD

**Issue by claytondaley** [alanjds/drf-nested-routers#107]
It would be helpful if the `NestedMixin` did a quality check on the lookup keyword (i.e. that all characters are valid for a regex group name) and provided a descriptive error message if they are not.  For example, including a hyphen in this value results in an error like:

```
django.core.exceptions.ImproperlyConfigured: "^parents/(?P<ui-parent_pk>[^/.]+)/childs/$" is not a valid regular expression: bad character in group name u'ui-parent_pk'
```

I've customized routers before so it was obvious to me what went wrong, but I doubt its obvious to first-time users of the package.  The issue came up because I normally use a pattern like:

```
api.register(parents', ParentViewSet, base_name='parent')
nested_router = NestedSingletonRouter(api, parents', lookup='parent')
nested_router.register(child', ParentChildViewSet, base_name='parent-child')
```

I needed to expose less permissive serializers for my UI so I ran into the error making "ui" versions.

```
api.register(parents', ParentViewSet, base_name='ui-parent')
nested_router = NestedSingletonRouter(api, parents', lookup='ui-parent')  # cannot use a hyphen in lookup
nested_router.register(child', ParentChildViewSet, base_name='ui-parent-child')
```

This may not be a huge issue, but it seems like an straightforward mistake to make and an easy one to catch/correct.  If this sounds reasonable, I should be able to get around to a PR.

**Comment by c17r** [comment]
Is `NestedSingletonRouter` a class you derived from `NestedSimpleRouter`?

**Comment by claytondaley** [comment]
Yes.  Sorry for the confusion.  It just customizes `routes`, but the same problem would exist for any router.

**Comment by claytondaley** [comment]
Well.  Technically it's a subclass of the `NestedMixin` and `SimpleRouter`.
