### ISSUE TITLE
Add convenience mixin to filter queryset based on its parents

### ISSUE THREAD

**Issue by joeribekker** [alanjds/drf-nested-routers#111]
I noticed that the documentation states that you can manually filter the queryset based on its parents, when using nested resources. If you're using a nested ``Serializer``, you most likely specify its ``parent_lookup_kwargs``. This ``dict`` contains all information to filter the queryset in a generic way.

I was looking for this but didn't find any helpers for this in the library. You can simply add the mixin below, to your ``ViewSet`` and it works:

```python
class NestedViewSetMixin(object):
    def get_queryset(self):
        """
        Filter the ``QuerySet`` based on its parents.
        """
        queryset = super().get_queryset()
        if hasattr(self.serializer_class, 'parent_lookup_kwargs'):
            orm_filters = {}
            for query_param, field_name in self.serializer_class.parent_lookup_kwargs.items():
                orm_filters[field_name] = self.kwargs[query_param]
            return queryset.filter(**orm_filters)
        return queryset
```

**Comment by joeribekker** [comment]
There ya go, forgot to support Django 1.8, hence multiple commits but now squashed.

**Comment by alanjds** [comment]
Closing, as the feature was merged.
