### ISSUE TITLE
New version ?

### ISSUE THREAD

**Issue by razvanbretoiu** [alanjds/drf-nested-routers#127]
Hi, 
I install the library via `pip` with the latest version: `0.90.2`, but this version doesn't have all the code from master. I need this PR #116 in my app, can you cut a new version ?

Btw, great library !

**Comment by alanjds** [comment]
You are right. The actual version is very dated. Thanks for the remind

**Comment by alanjds** [comment]
Done. Released over https://github.com/alanjds/drf-nested-routers/commit/8c48cae40522612debaca761503b4e1a6f1cdba4

**Comment by alanjds** [comment]
https://pypi.org/project/drf-nested-routers/ : drf-nested-routers 0.91
