### ISSUE TITLE
Nested lookups are always by id

### ISSUE THREAD

**Issue by thedrow** [alanjds/drf-nested-routers#13]
There should be an option to set the lookup to another field.

**Comment by jsenecal** [comment]
@all I wkow its been a while but if you have some usable use cases I could work on this :)

**Comment by ryanhiebert** [comment]
If I understand this problem correctly, I think it would be resolved if the proposed idea of #37 were merged. This appears to actually have been a bug in Django Rest Framework, one that was duplicated in this version of `lookup_value_regex`. Dropping our version in favor of the built-in one solved my issue that is like this.

**Comment by alanjds** [comment]
I am in favor of merging #37. Just awaiting a clean PR to merge.
