### ISSUE TITLE
NestedViewSetMixin should use `get_serializer_class` method instead of `serializer_class`

### ISSUE THREAD

**Issue by pddg** [alanjds/drf-nested-routers#133]
GenericAPIView and GenericViewSet implement `get_serializer_class` method to provide dynamic behavior of serializer class. Its documentation is here: https://www.django-rest-framework.org/api-guide/generic-views/#get_serializer_classself

This change do not affect default behavior of this module. `get_serializer_class` returns its class attribute (`serializer_class`) by default. 

I patched this, but in my environment, test with `tox` always fail with or without any changes. May I open the PR?

**Comment by alanjds** [comment]
Well, please open the PR. I am a bit absent on the discussions as am not using the lib on active projects. But people always benefit from each other efforts and feedbacks.
