### ISSUE TITLE
non model at 3 levels

### ISSUE THREAD

**Issue by mao-shonen** [alanjds/drf-nested-routers#165]
Sorry, I'm not that familiar with DRF.
I tried to follow the example.
At the third level.
Repeated errors on NestedHyperlinkedRelatedField
(Normal when using models, error is when I try non-models)
I referenced some other questions and answers, and I finally tried
```python
record = NestedHyperlinkedRelatedField(
    view_name='cloud-domain-record-detail',
    read_only=True,
    lookup_url_kwarg='domain_pk',
    parent_lookup_kwargs={'domain_pk': 'domain__pk'},
)
```

Can you please fill in the example of the serializer part of the 3 level non-model?
Or which direction I should go to find the answer.

**Comment by mao-shonen** [comment]
After my repeated attempts.
I confirmed that https://www.django-rest-framework.org/api-guide/reverse/ will solve my problem.

If there are other people who want to use Hyperlinks but use non-models, they can refer to

**Comment by mzhiwei** [comment]
class InspectionAreaInfoSerializer(NestedHyperlinkedModelSerializer):

    parent_lookup_kwargs = {
        'inspection_pk': 'inspectionarea__inspection_name__pk',
        'area_pk': 'inspectionarea__pk',
    }
    url = NestedHyperlinkedIdentityField(
        view_name='areasinfos-detail',
        # lookup_field='id',
        parent_lookup_kwargs={
            'inspection_pk': 'inspectionarea__inspection_name__pk',
            'area_pk': 'inspectionarea__pk',

        }
    )
