### ISSUE TITLE
Please extend example with NameserverViewSet

### ISSUE THREAD

**Issue by artem-fedosov** [alanjds/drf-nested-routers#17]
Thank you for coding this useful thing. I have a suggestion because I faced a problem while experimenting with your app.

Please consider extending example by providing NameserverViewSet code to make clear how {pk} and domain {domain_pk} should be used in ViewSets.  
General example of ViewSet is below, but how to enable filtering by {domain_pk} is not clear, so I have all Nameserver objects listed.

``` python
class NameserverViewSet(viewsets.ModelViewSet):
    queryset = Nameserver.objects.all()
    serializer_class = NameserverSerializer
```

**Comment by cameronblandford** [comment]
Bumping this! I would love to see an example for ModelViewSets.

**Comment by alanjds** [comment]
@artem-fedosov & @cameronblandford: The updated README from #108 does suits your needs? Can I close the issue here?

**Comment by cameronblandford** [comment]
@alanjds this looks great to me. I'm satisfied!

**Comment by artem-cliqz** [comment]
@alanjds I believe it does. Thanks for following up!

**Comment by alanjds** [comment]
Will close for now. Can be reopened.
