### ISSUE TITLE
Hyperlink field to nested ViewSet

### ISSUE THREAD

**Issue by DDevine** [alanjds/drf-nested-routers#19]
I have a nested comments setup like:
/api/item/{item_pk}/comments/{comment_pk}

Basically, I want to be able to use a HyperLinkedIdentityField (or whatever) to link to the comments provided by the nested router.

Is this currently doable in drf-nested-routers or should I go write a custom router?

**Comment by alanjds** [comment]
I guess #91 fixes it. Just released 0.90.0 with #91 merged. It could had fixed this one. Please reopen if needed.
