### ISSUE TITLE
Wrong file at PyPi

### ISSUE THREAD

**Issue by peter-stadler** [alanjds/drf-nested-routers#195]
PyPi has only a drf-nested-routers-0.92.linux-x86_64.tar.gz file containing files set up in a virtualenv ...
Its hash also does not correspond to the file as far as I can see.

**Comment by alanjds** [comment]
This is strange. I published the sdist & bdist_wheel. Will take a look. Thanks.

**Comment by alanjds** [comment]
Just released v0.92.1: https://pypi.org/project/drf-nested-routers/0.92.1/#files

Was generated from the tagged commit d896dd548f8063990f90d161433e283226f67a5b via `python setup.py sdist bdist_wheel`. Hope to had done it right this time :+1: 

Thanks again for the heads up, @peter-stadler.

**Comment by peter-stadler** [comment]
Thank you, it looks good :-)
