### ISSUE TITLE
Nested version of DefaultRouter

### ISSUE THREAD

**Issue by cancan101** [alanjds/drf-nested-routers#20]
drf-nested-routers includes a nested version of `SimpleRouter` but not `DefaultRouter`

**Comment by torstenrudolf** [comment]
is this released?

**Comment by sdornan** [comment]
Also would like to see this.

**Comment by alanjds** [comment]
The 1st version of DRF that officially supports drf-nested-routers (we!!) is 2.4 . [This code](https://github.com/tomchristie/django-rest-framework/blob/77867e1eef731853f6270660880b16696fbdec9d/rest_framework/routers.py#L220) ensures the compatibility.

Updated ``setup.py`` to need at least this version of DRF.

**Comment by alanjds** [comment]
Just released: https://pypi.python.org/pypi/drf-nested-routers/0.10.0

**Comment by alanjds** [comment]
Anyway, I want to provide a NestedDefaultRouter on the next release.

**Comment by alanjds** [comment]
NestedDefaultRouter has created on branch `defaultrouter`. Still needs tests.

**Comment by alanjds** [comment]
Just released v0.90.0 with #91 on it, and #91 could had fixed this. Please take a look. Thanks for reporting
