### ISSUE TITLE
Do there any blockers to bump new release?

### ISSUE THREAD

**Issue by jramnai** [alanjds/drf-nested-routers#244]
We are looking forward to using `django-nested-routers` with Django 3.2 on [edX](https://github.com/edx).

The Master branch is already tested against Django 3.2.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by alanjds** [comment]
Hi, @jramnai. Thanks for the heads up.

>  Do there any chance a new version will be bumped soon?

Sure. The last change on `master` is dated from 7d ago. I use to wait at least a couple weeks before releasing versions, allowing people that target `master` to report newly introduced issues.

In meantime, could you do the development targeting the github master branch?

**Comment by jramnai** [comment]
@alanjds, do you think that it is a good time for the new release?

**Comment by alanjds** [comment]
Just released https://pypi.org/project/drf-nested-routers/0.93.4/

Thanks for the heads-up, @jramnai !
