### ISSUE TITLE
missing git tag for 0.93.4

### ISSUE THREAD

**Issue by felschr** [alanjds/drf-nested-routers#261]
While trying to update this package in nixpkgs, I noticed there is no tag for 0.93.4 but the version was published on PyPi.

**Comment by Fares-Harri** [comment]
..

**Comment by felschr** [comment]
@alanjds could you take a look at this?

**Comment by alanjds** [comment]
Sure. I am a bit busy this days, but will take a look :+1:

**Comment by alanjds** [comment]
> While trying to update this package in nixpkgs, I noticed there is no tag for 0.93.4 but the version was published on PyPi.

Hi again, @Fares-Harri.

Found that I just forgot to push the tag. It already existed in my local clone, yet not pushed.

Thanks for pointing out. It should be on Github right now: https://github.com/alanjds/drf-nested-routers/tree/v0.93.4
