### ISSUE TITLE
Support for Python and Django

### ISSUE THREAD

**Issue by Fares-Harri** [alanjds/drf-nested-routers#286]
Hello,

Does `drf-nested-routers` support the latest version of Python (3.11) and the latest version of Django (4.1) ?

They are not listed in the setup file but mentioned in the readme file.

**Comment by alanjds** [comment]
Hi @Fares-Harri. Thanks for reaching out.

It works indeed. And is being tested on CI, as seem in the tox.ini file.

Agreed that it was not specifier in the setup.py classifiers. Wondering if is better to get rid of the minor version classifyers and let only "Django 3 & 4 and Python 3" generic ones

**Comment by alanjds** [comment]
Hi @Fares-Harri. Thanks for reaching out.

It works indeed. And is being tested on CI, as seem in the tox.ini file.

Agreed that it was not specifier in the setup.py classifiers. Wondering if is better to get rid of the minor version classifyers and let only "Django 3 & 4 and Python 3" generic ones

**Comment by Fares-Harri** [comment]
@alanjds Thanks for your answer.

but what about this?

```
drf3.11: djangorestframework>=3.11,<3.12
drf3.12: djangorestframework>=3.12,<3.13
```

does the package support the latest versions on djangorestframework (3.13.1 or 3.14.0)?

**Comment by Fares-Harri** [comment]
@alanjds Thank you
