### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by Fares-Harri** [alanjds/drf-nested-routers#288]
Is there changelog file ?

**Comment by Greg-Hamel** [comment]
@Fares-Harri, there doesn't seem to be, however I'd recommend having a look at the commit messages on master, they are often times descriptive enough to provide the insight you require.

https://github.com/alanjds/drf-nested-routers/commits/master

**Comment by alanjds** [comment]
Yep. There is no changelog file. Several times I thought about adding one, but got unsure on how to tackle (or at least ease) the maintenance burden of it. Ended up perceiving the [towncrier](https://pypi.org/project/towncrier/) as the smoothest option, but not smooth enough to make contributors use as a condition to receive code :shrug:.

What do you think?

**Comment by Fares-Harri** [comment]
Thank you both

@alanjds Can you give us the setting file that you are using for the tools for this package?

**Comment by alanjds** [comment]
Hi, @Fares-Harri.

I just checked and the https://github.com/alanjds/drf-nested-routers/blob/master/setup.cfg is commited in the repo. Is also commited the `tox.ini` that GitHub uses on the CI.
