### ISSUE TITLE
NestedViewSetMixin looks into the request object when generating a schema

### ISSUE THREAD

**Issue by dickermoshe** [alanjds/drf-nested-routers#291]
I have an endpoint that points to `/schema` that generates a schema using `drf_spectacular`.
The `NestedViewSetMixin.get_queryset` function checks  that we don't inspect the request when we aren't actually calling the viewset (e.g. `/users`) https://github.com/alanjds/drf-nested-routers/blob/fa3d4460ec2ef069e67b6ee612797e2e1ec57854/rest_framework_nested/viewsets.py#L49-L50

However `NestedViewSetMixin.initialize_request` does not.
I created a PR to add this same function to `initialize_request`. 

See here: https://github.com/alanjds/drf-nested-routers/pull/290

Please let me know if you will have time to merge this.
Thanks

**Comment by alanjds** [comment]
Closing, as #290 is merged already.
