### ISSUE TITLE
HyperlinkedRelatedField doesn't work

### ISSUE THREAD

**Issue by alexmakeev** [alanjds/drf-nested-routers#40]
1) you assume that there is some "domain" foreign key field in the model
2) you have a mistake "domain_lokup_field" at line 58, rest_framework_nested/relations.py

**Comment by alexmakeev** [comment]
Take a look at http://drf-toolbox.readthedocs.org/en/latest/nested.html

**Comment by alanjds** [comment]
Thanks for reporting.

This `relations.py` is an old contributed module and I had not used it by myself. Kept because drf-nested-routers have no deprecation policy (yet). Would love if someone needing it could fix.

My gut says to wipe the file and rewrite, anyway...

**Comment by alanjds** [comment]
@alexmakeev This is very nice! The way this RelatedField works is just how it should, IMHO.

The way the routers work is clean too, but is too much code and magic for me ;)
https://github.com/feedmagnet/drf-toolbox/blob/master/drf_toolbox/routers.py#L18
What you think?

Do you think that is better to just copy over this?
https://github.com/feedmagnet/drf-toolbox/blob/master/drf_toolbox/serializers/fields/related.py

**Comment by alexmakeev** [comment]
Found some bugs in drf-toolbox too (it relies on abandoned interface of drf)
Digging deeper found another solution that works nice: http://chibisov.github.io/drf-extensions/docs/

**Comment by alanjds** [comment]
I tried to put drf-nested-routers into main DRF, but the creator preferred to keep separated, and he agreed on one internal API change that I needed to be kept. The history is somewhere on the issues log...

This drf-extensions I already had heard by someone asking about a project merge, but it seemed to complicated to use for me. Maybe I should take another look.

**Comment by alanjds** [comment]
I think the drf-nested-routers needs something like NestedViewSetMixin...

**Comment by alanjds** [comment]
Anyway, I had no found there a HyperlinkRelated for nested resources. So, this ticket is still valid :)

**Comment by alexmakeev** [comment]
I didn't find it too, soo have wrote my own. Its here: https://github.com/chibisov/drf-extensions/issues/67
Sorry for russian =) At the bottom there is an example of use

**Comment by alanjds** [comment]
Hum...

Let me try to undestand: Based on the following structure of drf-nested-routers, how should I refer to Nameservers into a Domain serializer?

```
\domain\ <- Domains list
\domain\{pk}\ <- One domain, from {pk]
\domain\{domain_pk}\nameservers\ <- Nameservers of domain from {domain_pk}
\domain\{domain_pk}\nameservers\{pk} <- Specific nameserver from {pk}, of domain from {domain_pk}
```

**Comment by jsenecal** [comment]
@alanjds unless @alexmakeev still has this issue, I think you can safely close it for lack of response since I rewrote the field anyways.

**Comment by alanjds** [comment]
Closing the issue.

@alexmakeev: Feel free to reopen, but come to talk on gitter (on the front page button) before. Maybe what you want is already done...
