### ISSUE TITLE
0.9.1 release

### ISSUE THREAD

**Issue by lig** [alanjds/drf-nested-routers#46]
It's been a while since the 0.9.0 release.

Please release current master state as 0.9.1 or whatever release as it looks pretty stable.

**Comment by alanjds** [comment]
Ok. Will do so on the weekend.

Thanks for remind me

**Comment by matthewhochler** [comment]
Any update? Would love to not have `-e git://github.com/alanjds/drf-nested-routers.git#egg=drf-nested-routers` in my requirements anymore. :smiley:

**Comment by alanjds** [comment]
not yet ;)

**Comment by izzybelll** [comment]
What version of the DRF does this work for? I'm having problems getting this to work on DRF 3.2.2 :(

**Comment by alanjds** [comment]
Have not tested on 3+. As aways, I plan to, but had no time to do it.

**Comment by izzybelll** [comment]
Thanks so much for making this extension btw! Right now I'm using Python 2.7.10 with Django 1.8.4 and Rest Framework 2.4.6. I'm not understanding what goes in the ellipses of the example for viewsets:

class NameserverViewSet(viewsets.ViewSet):
    def list(self, request, domain_pk=None):
        nameservers = self.queryset.filter(domain=domain_pk)
        (...)
        return Response([...])

    def retrieve(self, request, pk=None, domain_pk=None):
        nameservers = self.queryset.get(pk=pk, domain=domain_pk)
        (...)
        return Response(serializer.data) 

I followed this example: 

class ClientViewSet(viewsets.ViewSet):
    serializer_class = ClientSerializer

    def list(self, request,):
        queryset = Client.objects.filter()
        serializer = ClientSerializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        queryset = Client.objects.filter()
        client = get_object_or_404(queryset, pk=pk)
        serializer = ClientSerializer(client)
        return Response(serializer.data)

class MailDropViewSet(viewsets.ViewSet):
    serializer_class = MailDropSerializer

    def list(self, request, client_pk=None):
        queryset = MailDrop.objects.filter(client=client_pk)
        serializer = MailDropSerializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk=None, client_pk=None):
        queryset = MailDrop.objects.filter(pk=pk, client=client_pk)
        maildrop = get_object_or_404(queryset, pk=pk)
        serializer = MailDropSerializer(maildrop)
        return Response(serializer.data)

and ended up with errors which I can post as soon as I get online properly.. Thanks once again!!!

**Comment by alanjds** [comment]
@izzybelll In the elipsis goes your own code. First, try to make it work without the nested stuff.

If wanting, take a look on the [default implementation](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/mixins.py#L39) of DRF

**Comment by alanjds** [comment]
@lig, @matthewhochler: Just released: [v0.10.0](https://pypi.python.org/pypi/drf-nested-routers/0.10.0)

May I ask you to suggest a roadmap for v0.11 and v1.0 ?

Thanks for the patience.
