### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by jsenecal** [alanjds/drf-nested-routers#47]
Hi there, 

Is this project still alive? or has it been superseded by other projects like http://chibisov.github.io/drf-extensions/ ?

Thanks!

**Comment by matthewhochler** [comment]
Still alive! @alanjds just pushed a new release: https://github.com/alanjds/drf-nested-routers/issues/46#issuecomment-134002285

**Comment by jsenecal** [comment]
Well, thanks @alanjds

**Comment by alanjds** [comment]
Hi, @jsenecal.

Well, depends on your definition of "Alive". I use it. It powers at least my webapp www.apiregistro.com.br,  and have a mention on DRF docs and a compatible interface on DRF specifically for it to work. I just released 0.10 yesterday, on feedback of the community.

However, the docs are just the README and comments on the issues. There is no roadmap nor wishlist right now.

For me, it is far from dead, as I keep reviewing and accepting PRs.

Anyway, I did not noticed the `drf-extensions` nested routers the last time I looked at. I specially liked the NestedViewSetMixin, something I wanted for a bit of time.

**Comment by alanjds** [comment]
I still think it is simple enough to be relevant, on the Unix KISS moto. But if going to deprecate, you can expect me to publish a migration plan to something else, at least.

**Comment by jsenecal** [comment]
Thanks @alanjds, I was asking because I liked the simplicity of your implementation better than what is currently available and was worried that you might not be available to merge PRs/fix issues etc.

I am an active colaborator on https://github.com/django-json-api/django-rest-framework-json-api and I was going to implement resource linking based on nested relationships - I am going to have your project used as a dependency for doing so. 

I will most likely endup contributing some code to your repo as well once I get use to the way you are doing things ;)

**Comment by alanjds** [comment]
@jsenecal You are welcome :)
