### ISSUE TITLE
Enable Gitter for this repo

### ISSUE THREAD

**Issue by jsenecal** [alanjds/drf-nested-routers#48]
Hello @alanjds ,

It would be nice to enable [Gitter](https://gitter.im/) for this repo so we could discuss ideas and such.

I have few things that I would personally like to ask but don't feel like an issue would be adequate.

**Comment by alanjds** [comment]
Hi. I will take a look. Thakns for suggesting.

**Comment by alanjds** [comment]
Done: #49

Thanks for pointing it.
