### ISSUE TITLE
Incompatible with DRF > 3.0.2

### ISSUE THREAD

**Issue by Aldarn** [alanjds/drf-nested-routers#55]
This package is incompatible with Django Rest Framework since version 3.0.3. An import in `relations.py` that drf-nested-routers uses in DRF has been removed and as such it now fails with an ImportError:

```python
from rest_framework.compat import urlparse
```

You can see the change in DRF here:

https://github.com/tomchristie/django-rest-framework/commit/b33a6cbff16e5a28a1a696e2ac617303da181720#diff-ce493f71b3679e91b72126c168670399

I propose this to be fixed by instead using the Django module initially intended to be used:

```python
from django.utils.six.moves.urllib import parse as urlparse
```

I will submit a PR for this, please accept if you agree with my hypothesis and conclusion.

**Comment by Aldarn** [comment]
OK I just noticed master has changed all this and maybe it works with the latest DRF? Can we get a release of this?

**Comment by alanjds** [comment]
Fair. Thanks for pointing.

Will release the new version as soon as I got some spare time. Hopefully on this weekend.

**Comment by kiote** [comment]
Hi! Faced with the same problem. Any chance to fix?

**Comment by Aldarn** [comment]
The master branch works with the latest DRF, you can install it with pip:

`pip install -e git+git://github.com/alanjds/drf-nested-routers@master#egg=drf-nested-routers-master`

If you want this in a requirements file simply add:

`-e git://github.com/alanjds/drf-nested-routers@master#egg=drf-nested-routers-master`

**Comment by kiote** [comment]
Cool! Thanks @Aldarn

**Comment by alanjds** [comment]
@Aldarn, The actual master version should got it fixed. Can you please confirm and close the issue?

Thanks.

**Comment by alanjds** [comment]
Will close. @Aldarn please reopen if still broken. Thanks.
