### ISSUE TITLE
Document how to run unit tests

### ISSUE THREAD

**Issue by sorenh** [alanjds/drf-nested-routers#61]
Can you please document how to run the unit tests? I managed to get the router tests running, but it was pretty awkward. Starting with a fresh virtualenv, what needs to be installed, etc.?

**Comment by alanjds** [comment]
I am in process of setting tox + travis-ci. Should be "tox" and everything tests itself, I guess.

**Comment by alanjds** [comment]
Done with tox + travis-ci. Run "tox" and it works. I am running only Py27+Django1.7+DRF3 locally, to speedup the tests:
```
$ tox -e py27-django1.6-drf3.0
```

But yes, the docs should be updated with instructions.
