### ISSUE TITLE
How to use HyperlinkedIndentityField in a 2 level nested routing

### ISSUE THREAD

**Issue by AncAinu** [alanjds/drf-nested-routers#67]
If I take your exemple:

`/clients/{client_pk}/maildrops/{maildrop_pk}/recipients/`

what would be the usage of `HyperlinkedIndentityField` into let's say "MaildropSerializer" so it would display me this address into a field "recipients" ?

I didn't have any issue implementing it on the root level (in this examplem it would be clients), but I can't figure how to do in nested level

**Comment by alanjds** [comment]
+1

**Comment by alanjds** [comment]
Just released 0.90.0 with #91 merged. It should had fixed this one. Please reopen if needed.
