### ISSUE TITLE
404

### ISSUE THREAD

**Issue by murdav** [alanjds/drf-nested-routers#80]
Hello,

Django 1.9.5
djangorestframework==3.4.4
drf-nested-routers==0.11.1

The code:
```
router.register('products', ProductViewSet, base_name='products')
product_router = routers.NestedSimpleRouter(router, 'products', lookup='product')
product_router.register('scarfs', ScarfViewSet, base_name='scarfs')

# I removed urlpatterns = patterns('', 
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^', include(product_router.urls)),
****
```

http://localhost:8000/api/v1/products/33/scarfs

return 404, but it should work.
I suppose it's linked to this https://github.com/alanjds/drf-nested-routers/pull/72.

Ideas?

Thanks,

D

**Comment by alanjds** [comment]
Just to be sure... There is a scarf pk=33 ?

Can you paste here the routes shown by the debug interface?

**Comment by alanjds** [comment]
Does it work on the branch of #72 ?

**Comment by murdav** [comment]
Dear @alanjds,
I tried several times when I updated Django and I continued to get 404, but:
I reinstalled drf-nested-routers (pip -U); I removed all *.pyc files from the project and from the virtualenv site-packages/and now it works....

D

**Comment by alanjds** [comment]
??

Nice. Problem solved.

:)
