### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fladi** [alanjds/drf-nested-routers#83]
Will there be a new release in the near future? I would like to package drf-nested-routers for Debian.

**Comment by alanjds** [comment]
There will be, but I am waiting the resolution of https://github.com/alanjds/drf-nested-routers/pull/72 before issuing a new version.

What do you think is the best to do?

**Comment by Nijhazer** [comment]
+1 to this. Getting started with this library is a little painful, as the README provides usage examples using imports that don't exist in the current release.

**Comment by blag** [comment]
The version in git `master` works perfectly for me. The weirdest thing was installing from PyPI, working off of the README on GitHub, and having stuff not work.

**Comment by auvipy** [comment]
A new PyPi release is evident

**Comment by alanjds** [comment]
Now I will wait some sunsets for people to perceive if this imminent release breaks their systems, and try to adapt the thing and so. Then release to PyPI. Will be the 0.90 I guess,

**Comment by alanjds** [comment]
Will close this in favor of #91.
