### ISSUE TITLE
drf-nested-routers 0.11.1 tarball uploaded to PyPI seems not to contain rest_framework_nested/serializers.py

### ISSUE THREAD

**Issue by shanx** [alanjds/drf-nested-routers#90]
If I clone the project and run `python setup.py sdist` the created tarball does contain serializers.py

**Comment by alanjds** [comment]
This is strange. The packages are collected this way: https://github.com/alanjds/drf-nested-routers/blob/master/setup.py#L27

I am not able to investigate this right now, but would love to test and merge a PR if someone discovers this to be a bug. And thanks @shanx for reporting.

**Comment by shanx** [comment]
Thanks for responding! So I already forked your repo in order to fix this and add a PR. But doing a `python setup.py sdist` locally (which is in turn what will be uploaded) actually generates a tarball containing serializer.py. So the only thing I can imagine is that something specific went wrong on your development machine. 

I think the best way to deal with this is that you run the `python setup.py sdist` locally and see if the tarball contains the serializer.py file. If so the best thing would be to bump the version to 0.11.2 and upload a new sdist to PyPI. That should be the only thing required to fix the issue. Interesting that nobody found this problem earlier...

**Comment by alanjds** [comment]
Sorry, maybe I had read too fast. You says that the _right_ thing is the file to BE or NOT BE on the tarball?

**Comment by shanx** [comment]
So on PyPI the file doesn't exist in the tarball.

When I try to reproduce the error, the file does end up in the tarball.

**Comment by alanjds** [comment]
Hum... Maybe it is a sign that the 1) serializers.py are not being used by anyone 2) everybody using it clones from Github.

There is [some move](https://github.com/alanjds/drf-nested-routers/pull/88) towards removing the actual serializer to better ones, but with a backwards-incompatible API. Is on #88.

What you think about it?
I am asking because I had not saw people talking about the serializers, so I do not know if this change would harm or help more the people

**Comment by alanjds** [comment]
Ah, ok. Got it. Maybe your machine is broken, maybe my tarball is broken. But the thing SHOULD be there in your opinion.

**Comment by shanx** [comment]
Well it exists here: https://github.com/alanjds/drf-nested-routers/blob/master/rest_framework_nested/serializers.py right? So it should be in the tarball here: https://pypi.python.org/packages/ee/0f/fdb382c50ad174a4d9ec8a55c955cb31c3ec619e18665b89c92258dbb220/drf-nested-routers-0.11.1.tar.gz#md5=2edcb0d992ea57c3957f5e968cf4b10f  right? :)

**Comment by c17r** [comment]
The latest version on pypi is 0.11.1 which was uploaded on 2015-11-17.

serializers.py wasn't added (by me) until 2016-09-13 and wasn't merged in till 2016-11-07.

Issue #83 says @alanjds is waiting on #72 before cutting a new release.

**Comment by c17r** [comment]
And my opinion would be finishing/merging #88 before cutting a new release would be the way to go.

**Comment by shanx** [comment]
Ah right, that explains the issue. And I understand why you guys are waiting before doing a release. Closing the issue. Thanks for explaining!
