### ISSUE TITLE
Finding URL with reverse not working when using url namespaces

### ISSUE THREAD

**Issue by frennkie** [alanjds/drf-nested-routers#94]
I have the following setup which fails:
```
url(r'^v3/', include(router.urls, namespace="api-v3")),
reverse("api-v3:tag-list", kwargs={"project_pk": obj}))
```

Error message:
```
NoReverseMatch: Reverse for 'tag-list' with arguments '()' and keyword arguments '{'project_pk': 'viel'}' not found. 0 pattern(s) tried: []
```

When I change it to the following it works:
```
url(r'^v3/', include(router.urls)),
reverse("tag-list", kwargs={"project_pk": obj})
```

Are namespaces not supported by drf-nested-routers? Could this be fixed?

**Comment by alanjds** [comment]
Hi. I remember to had opened some similar issue over djangorestframework directly some time ago, and there was some talk about how this should be fixed or should not. I bet it is a DRF's issue, not nested-routers one, but I could be wrong.

Will try to find the specific issue and mention it here for you to check, but I tend to be slow this days and you may be very faster than I by yourself.

I will close for now, but please reopen if you found there and still think the error to be here.
